---
- hosts: idrac
  connection: local
  gather_facts: False

  vars:
    ansible_python_interpreter: python

  tasks:
  - name: Set manager attributes
    include_role:
      name: idrac_manager_attributes
    tags:
      - idrac-manager-attributes
