---
- hosts: poweredge
  connection: local
  gather_facts: False

  tasks:
  - name: get system facts
    redfish_facts:
      baseuri: "{{inventory_hostname}}"
      username: "{{ idrac_user }}"
      password:  "{{ idrac_password }}"
      category:
        - Systems
      command:
        - GetSystemInventory
        - GetPsuInventory
        - GetCpuInventory
        - GetMemoryInventory
        - GetNicInventory
        - GetStorageControllerInventory
        - GetDiskInventory
        #- GetVolumeInventory
        - GetBiosAttributes
        - GetBootOrder
        #- GetBootOverride
